In [3]:
import pandas as pd
pharma_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Training_set_begs.csv')
test_data = pd.read_csv('https://raw.githubusercontent.com/dphi-official/Datasets/master/pharma_data/Testing_set_begs.csv')

In [ ]:
pharma_data.head()

ID_Patient_Care_Situation  Diagnosed_Condition  Patient_ID  \
0                      22374                    8        3333   
1                      18164                    5        5740   
2                       6283                   23       10446   
3                       5339                   51       12011   
4                      33012                    0       12513   

  Treated_with_drugs  Patient_Age  Patient_Body_Mass_Index Patient_Smoker  \
0                DX6           56                18.479385            YES   
1               DX2            36                22.945566            YES   
2                DX6           48                27.510027            YES   
3               DX1             5                19.130976             NO   
4                NaN          128                 1.348400     Cannot say   

  Patient_Rural_Urban Patient_mental_condition    A    B    C    D    E    F  \
0               URBAN                   Stable  1.0  0.0  0.0  0.0  1.0  0.0   
1               RURAL                   Stable  1.0  0.0  0.0  0.0  0.0  0.0   
2               RURAL                   Stable  1.0  0.0  0.0  0.0  0.0  0.0   
3               URBAN                   Stable  1.0  0.0  0.0  0.0  0.0  0.0   
4               RURAL                   Stable  0.0  0.0  0.0  0.0  0.0  0.0   

     Z  Number_of_prev_cond  Survived_1_year  
0  0.0                  2.0                0  
1  0.0                  1.0                1  
2  0.0                  1.0                0  
3  0.0                  1.0                1  
4  1.0                  1.0                1

In [5]:
test_data.head()

ID_Patient_Care_Situation  Diagnosed_Condition  Patient_ID  \
0                      19150                   40        3709   
1                      23216                   52         986   
2                      11890                   50       11821   
3                       7149                   32        3292   
4                      22845                   20        9959   

  Treated_with_drugs  Patient_Age  Patient_Body_Mass_Index Patient_Smoker  \
0               DX3            16                29.443894             NO   
1                DX6           24                26.836321             NO   
2           DX4 DX5            63                25.523280             NO   
3                DX6           42                27.171155             NO   
4               DX3            50                25.556192             NO   

  Patient_Rural_Urban Patient_mental_condition    A    B    C    D    E    F  \
0               RURAL                   Stable  1.0  0.0  0.0  0.0  1.0  0.0   
1               URBAN                   Stable  1.0  1.0  0.0  0.0  0.0  0.0   
2               RURAL                   Stable  1.0  0.0  0.0  0.0  1.0  0.0   
3               URBAN                   Stable  1.0  0.0  1.0  0.0  1.0  0.0   
4               RURAL                   Stable  1.0  0.0  0.0  0.0  0.0  0.0   

     Z  Number_of_prev_cond  
0  0.0                  2.0  
1  0.0                  2.0  
2  0.0                  2.0  
3  0.0                  3.0  
4  0.0                  1.0

In [6]:
print(pharma_data.shape)
print(test_data.shape)

Pharma_data = pharma_data.drop('Survived_1_year', axis=1)
print(Pharma_data.shape)
data = pd.merge(Pharma_data, test_data, how='outer')

print(data.shape)
data.head()

(23097, 18)
(9303, 17)
(23097, 17)
(32400, 17)


ID_Patient_Care_Situation  Diagnosed_Condition  Patient_ID  \
0                      22374                    8        3333   
1                      18164                    5        5740   
2                       6283                   23       10446   
3                       5339                   51       12011   
4                      33012                    0       12513   

  Treated_with_drugs  Patient_Age  Patient_Body_Mass_Index Patient_Smoker  \
0                DX6           56                18.479385            YES   
1               DX2            36                22.945566            YES   
2                DX6           48                27.510027            YES   
3               DX1             5                19.130976             NO   
4                NaN          128                 1.348400     Cannot say   

  Patient_Rural_Urban Patient_mental_condition    A    B    C    D    E    F  \
0               URBAN                   Stable  1.0  0.0  0.0  0.0  1.0  0.0   
1               RURAL                   Stable  1.0  0.0  0.0  0.0  0.0  0.0   
2               RURAL                   Stable  1.0  0.0  0.0  0.0  0.0  0.0   
3               URBAN                   Stable  1.0  0.0  0.0  0.0  0.0  0.0   
4               RURAL                   Stable  0.0  0.0  0.0  0.0  0.0  0.0   

     Z  Number_of_prev_cond  
0  0.0                  2.0  
1  0.0                  1.0  
2  0.0                  1.0  
3  0.0                  1.0  
4  1.0                  1.0

In [7]:
data.isnull().sum()

ID_Patient_Care_Situation       0
Diagnosed_Condition             0
Patient_ID                      0
Treated_with_drugs             13
Patient_Age                     0
Patient_Body_Mass_Index         0
Patient_Smoker                  0
Patient_Rural_Urban             0
Patient_mental_condition        0
A                            1235
B                            1235
C                            1235
D                            1235
E                            1235
F                            1235
Z                            1235
Number_of_prev_cond          1235
dtype: int64

In [8]:
data.fillna(0, inplace=True)

In [9]:
data.isna().sum()

ID_Patient_Care_Situation    0
Diagnosed_Condition          0
Patient_ID                   0
Treated_with_drugs           0
Patient_Age                  0
Patient_Body_Mass_Index      0
Patient_Smoker               0
Patient_Rural_Urban          0
Patient_mental_condition     0
A                            0
B                            0
C                            0
D                            0
E                            0
F                            0
Z                            0
Number_of_prev_cond          0
dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

patient_smoker = le.fit_transform(data['Patient_Smoker'])
data['Patient_Smoker'] = patient_smoker


patient_rural_urban = le.fit_transform(data['Patient_Rural_Urban'])
data['Patient_Rural_Urban'] = patient_rural_urban

patient_mental_condition = le.fit_transform(data['Patient_mental_condition'])
data['Patient_mental_condition'] = patient_mental_condition

data= data[['ID_Patient_Care_Situation','Diagnosed_Condition','Patient_ID','Patient_Age','Patient_Body_Mass_Index',
                'Patient_Smoker','Patient_Rural_Urban','Patient_mental_condition','A','B','C','D','E','F','Z', 'Number_of_prev_cond' ]]
data.head()

ID_Patient_Care_Situation  Diagnosed_Condition  Patient_ID  Patient_Age  \
0                      22374                    8        3333           56   
1                      18164                    5        5740           36   
2                       6283                   23       10446           48   
3                       5339                   51       12011            5   
4                      33012                    0       12513          128   

   Patient_Body_Mass_Index  Patient_Smoker  Patient_Rural_Urban  \
0                18.479385               2                    1   
1                22.945566               2                    0   
2                27.510027               2                    0   
3                19.130976               1                    1   
4                 1.348400               0                    0   

   Patient_mental_condition    A    B    C    D    E    F    Z  \
0                         0  1.0  0.0  0.0  0.0  1.0  0.0  0.0   
1                         0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
2                         0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
3                         0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
4                         0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   

   Number_of_prev_cond  
0                  2.0  
1                  1.0  
2                  1.0  
3                  1.0  
4                  1.0

In [26]:
X = data.iloc[0:23097,:]
y = pharma_data.Survived_1_year



In [27]:
from sklearn.model_selection import train_test_split

In [146]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.4027, random_state=47)




In [140]:
from sklearn.linear_model import LogisticRegression

In [141]:
log_model = LogisticRegression()

In [142]:
log_model.fit(X_train, y_train)

LogisticRegression()

In [145]:
X_test = data.loc[23098:,:]
y_pred = log_model.predict(X_test)
print(log_model.predict(X_test))

[1 1 1 ... 1 1 1]


In [135]:
X_test["prediction"] = y_pred
submission = X_test[["prediction"]]
submission.to_csv("Sample_Submission.csv", index = False)

C:\Users\Tunji\AppData\Local\Temp/ipykernel_5552/2355602453.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test["prediction"] = y_pred


In [60]:
y_pred

array([1, 1, 1, ..., 1, 1, 1], dtype=int64)

In [136]:
y_pred.value_counts

AttributeError: 'numpy.ndarray' object has no attribute 'value_counts'

In [53]:
len(y_pred)


9302

In [100]:
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,y_pred))



0.6355622446785637


In [63]:
from sklearn.metrics import confusion_matrix

In [101]:
confusion_matrix(y_test, y_pred)

array([[   2, 3390],
       [   0, 5910]], dtype=int64)

In [102]:
from sklearn.metrics import f1_score 
print("F1 Score: ",f1_score(y_test, y_pred))

F1 Score:  0.777120315581854


In [ ]:
X